name: Building

on: [push, workflow_dispatch]

env:
  SOLUTION_FILE_PATH: .
  
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      uses: microsoft/setup-msbuild@v2

    - name: Restore Nuget
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Compile
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
         
    - name: Upload CTFAK UnEx
      uses: actions/upload-artifact@v3
      with:
       name: CTFAK
       path: D:\a\CTFAK-UnEx\CTFAK-UnEx\build
